### ISSUE TITLE
pgSimplifyInflector warnings with supabase

### ISSUE THREAD

**Issue by stlbucket** [benjie/crystal#509] opened 2023-09-14 23:33 UTC
This is running on supabase.  This is all coming from the vault table in one of the supabase-specific schemas.

```
ℹ Vite client warmed up in 3992ms                                                                                                 4:29:51 PM
Plugin 'PgSimplifyInflectionPlugin' attempted to overwrite inflector 'patchField', but no such inflector exists.
Plugin 'PgSimplifyInflectionPlugin' attempted to overwrite inflector 'updateByKeysField', but no such inflector exists.
Plugin 'PgSimplifyInflectionPlugin' attempted to overwrite inflector 'deleteByKeysField', but no such inflector exists.
Plugin 'PgSimplifyInflectionPlugin' attempted to overwrite inflector 'updateByKeysInputType', but no such inflector exists.
Plugin 'PgSimplifyInflectionPlugin' attempted to overwrite inflector 'deleteByKeysInputType', but no such inflector exists.
Plugin 'PgSimplifyInflectionPlugin' attempted to overwrite inflector 'updateNodeField', but no such inflector exists.
Plugin 'PgSimplifyInflectionPlugin' attempted to overwrite inflector 'deleteNodeField', but no such inflector exists.
Plugin 'PgSimplifyInflectionPlugin' attempted to overwrite inflector 'updateNodeInputType', but no such inflector exists.
Plugin 'PgSimplifyInflectionPlugin' attempted to overwrite inflector 'deleteNodeInputType', but no such inflector exists.
getAttributes() called on constraint 'key_parent_key_fkey' (type = 'f'), but we could not find the constraint's table (oid = '25446') in the introspection results; returning empty array
getForeignAttributes() called on constraint 'key_parent_key_fkey' (type = 'f'), but we could not find the constraint's foreign table (oid = '25446') in the introspection results; returning empty array
getAttributes() called on constraint 'secrets_key_id_fkey' (type = 'f'), but we could not find the constraint's table (oid = '25696') in the introspection results; returning empty array
getForeignAttributes() called on constraint 'secrets_key_id_fkey' (type = 'f'), but we could not find the constraint's foreign table (oid = '25446') in the introspection results; returning empty array
^C%
```

**Comment by stlbucket** [comment] 2023-09-14 23:33
<img width="1260" alt="image" src="https://github.com/benjie/crystal/assets/2467892/d6cd119d-a39b-456f-aa60-f1a859bca2fd">

**Comment by stlbucket** [comment] 2023-09-14 23:39
I think that's everything on this topic I could mine from discord.

It could be something supabase is doing that is non-standard?

**Comment by benjie** [comment] 2023-09-15 15:29
```
Plugin 'PgSimplifyInflectionPlugin' attempted to overwrite inflector 'patchField', but no such inflector exists.
Plugin 'PgSimplifyInflectionPlugin' attempted to overwrite inflector 'updateByKeysField', but no such inflector exists.
Plugin 'PgSimplifyInflectionPlugin' attempted to overwrite inflector 'deleteByKeysField', but no such inflector exists.
Plugin 'PgSimplifyInflectionPlugin' attempted to overwrite inflector 'updateByKeysInputType', but no such inflector exists.
Plugin 'PgSimplifyInflectionPlugin' attempted to overwrite inflector 'deleteByKeysInputType', but no such inflector exists.
Plugin 'PgSimplifyInflectionPlugin' attempted to overwrite inflector 'updateNodeField', but no such inflector exists.
Plugin 'PgSimplifyInflectionPlugin' attempted to overwrite inflector 'deleteNodeField', but no such inflector exists.
Plugin 'PgSimplifyInflectionPlugin' attempted to overwrite inflector 'updateNodeInputType', but no such inflector exists.
Plugin 'PgSimplifyInflectionPlugin' attempted to overwrite inflector 'deleteNodeInputType', but no such inflector exists.
```

^ These errors are an indication that the simplify inflection plugin is running _before_ the inflectors are registered. This is unrelated to supabase; and likely it means that you've added the simplify inflection preset too early in the list - it should be near the end.

```
getAttributes() called on constraint 'key_parent_key_fkey' (type = 'f'), but we could not find the constraint's table (oid = '25446') in the introspection results; returning empty array
getForeignAttributes() called on constraint 'key_parent_key_fkey' (type = 'f'), but we could not find the constraint's foreign table (oid = '25446') in the introspection results; returning empty array
getAttributes() called on constraint 'secrets_key_id_fkey' (type = 'f'), but we could not find the constraint's table (oid = '25696') in the introspection results; returning empty array
getForeignAttributes() called on constraint 'secrets_key_id_fkey' (type = 'f'), but we could not find the constraint's foreign table (oid = '25446') in the introspection results; returning empty array
^C%
```

^ These issues typically occur when there are tables coming from extensions. We exclude tables from extensions, but apparently we might not exclude their constraints; see graphile/crystal#1750 

I'm going to close this as a duplicate of graphile/crystal#1750 for now.

**Closed by benjie** 2023-09-15 15:29 UTC
Labels: 👥 duplicate

**Comment by stlbucket** [comment] 2023-09-17 17:23
it seems to be a different reason for the inflector warnings

from my graphile.config.ts
```
const preset: GraphileConfig.Preset = {
  extends: [
    amber,
    makeV4Preset({
      simpleCollections: "both",
      disableDefaultMutations: true,
      dynamicJson: true
    }),
    PgSimplifyInflectionPreset,
    /* Add more presets here */
  ],
```

**Comment by benjie** [comment] 2023-09-18 12:15
It could be that you have disable mutations or something; are you able to reproduce in a PR to ouch-my-finger?

**Comment by stlbucket** [comment] 2023-09-18 17:02
I will try and make an isolated reproduction of it soon

This whole issue was just trying not to lose a couple things from our thread a couple weeks back - neither are show-stoppers.

**Comment by benjie** [comment] 2023-09-18 17:50
Tracking these things down will help other users so I appreciate the effort!
